# Generated by Django 5.0.4 on 2024-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskDesc',
            new_name='taskdesc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='tasktitle',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
